### ISSUE TITLE
Inline URL

### ISSUE THREAD

**Issue by borNfreee** [SimonWaldherr/micromarkdown.js#8]
Hi,

great parser!
I can't add support for inline URL, may be somebody could help me?

`http://test.com` -> `<a href="http://test.com">http://test.com</a>"`

**Comment by atleastimtrying** [comment]
@borNfreee I ended up wrapping the text in https://github.com/SoapBox/linkifyjs before passing it through micromarkdown, might be useful?

**Comment by borNfreee** [comment]
Yes. I did the same. Works as expected
